### ISSUE TITLE
你好，请问你的 TV 上使用什么 App，在哪里下载？

### ISSUE THREAD

**Issue by hezhongfeng** [kimwang1978/tvbox#1]
谢谢，原版TVBOX 好像不支持多仓

**Comment by kimwang1978** [comment]
是的，原版不支持多仓的。

下面这个页面上有个公众号，关注后，点击页面下方按钮可以找到下载位置。
https://github.com/kimwang1978/collect-tv-txt

**Comment by kimwang1978** [comment]
@hezhongfeng

**Comment by hezhongfeng** [comment]
妥了，谢谢。
